"""定数定義"""

PROJECT_ID = "monthly-pay-tax"
DATASET = "pay_reports"
USERS_TABLE = f"{PROJECT_ID}.{DATASET}.dashboard_users"
CHECK_LOGS_TABLE = f"{PROJECT_ID}.{DATASET}.check_logs"
GROUPS_MASTER_TABLE = f"{PROJECT_ID}.{DATASET}.groups_master"
MEMBERS_TABLE = f"{PROJECT_ID}.{DATASET}.members"
INITIAL_ADMIN_EMAIL = "yasushi-honda@tadakayo.jp"
COLLECTOR_URL = "https://pay-collector-209715990891.asia-northeast1.run.app/"
APP_GYOMU_TABLE = f"{PROJECT_ID}.{DATASET}.app_gyomu_reports"
APP_HOJO_TABLE = f"{PROJECT_ID}.{DATASET}.app_hojo_reports"
REIMBURSEMENT_VIEW = f"{PROJECT_ID}.{DATASET}.v_reimbursement_enriched"
MONTHLY_COMPENSATION_VIEW = f"{PROJECT_ID}.{DATASET}.v_monthly_compensation"
MEMBER_MASTER_TABLE = f"{PROJECT_ID}.{DATASET}.member_master"
