"""定数定義"""

PROJECT_ID = "monthly-pay-tax"
DATASET = "pay_reports"
USERS_TABLE = f"{PROJECT_ID}.{DATASET}.dashboard_users"
CHECK_LOGS_TABLE = f"{PROJECT_ID}.{DATASET}.check_logs"
GROUPS_MASTER_TABLE = f"{PROJECT_ID}.{DATASET}.groups_master"
SYNC_GROUPS_TABLE = f"{PROJECT_ID}.{DATASET}.dashboard_sync_groups"
MEMBERS_TABLE = f"{PROJECT_ID}.{DATASET}.members"
INITIAL_ADMIN_EMAIL = "yasushi-honda@tadakayo.jp"
COLLECTOR_URL = "https://pay-collector-209715990891.asia-northeast1.run.app/"
APP_GYOMU_TABLE = f"{PROJECT_ID}.{DATASET}.app_gyomu_reports"
APP_HOJO_TABLE = f"{PROJECT_ID}.{DATASET}.app_hojo_reports"
REIMBURSEMENT_VIEW = f"{PROJECT_ID}.{DATASET}.v_reimbursement_enriched"
MONTHLY_COMPENSATION_VIEW = f"{PROJECT_ID}.{DATASET}.v_monthly_compensation"
MEMBER_MASTER_TABLE = f"{PROJECT_ID}.{DATASET}.member_master"
GAS_BINDINGS_TABLE = f"{PROJECT_ID}.{DATASET}.gas_bindings"
# 予実管理機能 (PR-A で BQ 構築済み、PR-D で UI 連携)
TEAM_BUDGETS_TABLE = f"{PROJECT_ID}.{DATASET}.team_budgets"
TEAM_MONTHLY_EVAL_TABLE = f"{PROJECT_ID}.{DATASET}.team_monthly_eval"
TEAM_BUDGET_ACTUALS_VIEW = f"{PROJECT_ID}.{DATASET}.v_team_budget_actuals"
GYOMU_REPORTS_TABLE = f"{PROJECT_ID}.{DATASET}.gyomu_reports"
# 予実管理機能 PR-E (四半期×統括隊×カテゴリ) + PR-F (階層設定 UI)
TEAM_HIERARCHY_TABLE = f"{PROJECT_ID}.{DATASET}.team_hierarchy"
TEAM_HIERARCHY_COVERAGE_VIEW = f"{PROJECT_ID}.{DATASET}.v_team_hierarchy_coverage"
TEAM_BUDGETS_QUARTERLY_TABLE = f"{PROJECT_ID}.{DATASET}.team_budgets_quarterly"
FISCAL_QUARTER_UDF = f"`{PROJECT_ID}.{DATASET}`.fiscal_quarter"
LEADER_TEAM_TYPES: tuple[str, ...] = ("operating", "common")
